### ISSUE TITLE
Where do I get tfont files

### ISSUE THREAD

**Issue by peterennis** [adrientetar/Fonte#7]
The app only seems to load/save tfont files.
What are they?
I have ttf and can create ufo from trufont which
saves glif files.
How do I load something into Fonte to do
further testing?

![Capture747](https://user-images.githubusercontent.com/140737/70005436-79823500-151e-11ea-98d9-a87d857c3518.PNG)

**Comment by adrientetar** [comment]
You can import from UFO with [UFOConverter](https://github.com/trufont/tfont/blob/master/src/tfont/converters/ufoConverter.py) but currently not possible to export back to UFO.

**Comment by peterennis** [comment]
@adrientetar OK. I am still testing and learning, but I think Fonte is going in the right direction 👍

**Comment by adrientetar** [comment]
I been doing this for four years, so yeah. I started writing opentype compiler but it's not finished yet.
